"""Flask HTTP server wrapping ffmpeg for the video-processing-pipeline container.

This server runs inside a Cloudflare Container alongside the ffmpeg binary.
The Cloudflare Workflow sends HTTP requests to this server to perform
CPU-intensive video processing tasks. Each endpoint downloads an input file
from a presigned R2 GET URL, runs an ffmpeg command, and uploads the result
to a presigned R2 PUT URL.

Endpoints:
    GET  /health         — readiness probe; returns ``{"ok": true}``
    POST /transcode      — transcode any video to H.264/AAC MP4
    POST /extract-audio  — extract audio track to MP3
    POST /grayscale      — apply grayscale filter, preserve audio

Request body (all POST endpoints)::

    {"input_url": "<presigned-get-url>", "output_url": "<presigned-put-url>"}

Success response (HTTP 200)::

    {"ok": true, "duration_seconds": <float>}

Error response (HTTP 500, 504, or unhandled exception)::

    {"ok": false, "error": "<ExceptionType>", "detail": "<message>"}
    {"ok": false, "error": "<message>", "stderr": "<truncated-ffmpeg-stderr>"}

Error handling:
    A global ``@app.errorhandler(Exception)`` converts ALL unhandled exceptions
    to JSON rather than Flask's default HTML 500 page.  Without this, an SSL
    error during ``_download`` would silently return ``<!doctype html>`` which
    the Cloudflare Workflow then fails to ``.json()``, producing a misleading
    ``SyntaxError: Unexpected token '<'`` instead of the real cause.

Signal handling:
    tini acts as PID 1 and forwards SIGTERM to gunicorn which shuts down
    workers gracefully. The ``finally`` block in each route ensures temporary
    files are cleaned up even when a request is interrupted mid-flight.

Timeout:
    Each ffmpeg invocation has a 1800-second (30-minute) subprocess timeout.
    gunicorn's ``--timeout`` flag is also set to 1800 seconds to match.
"""

import os
import ssl
import subprocess
import sys
import tempfile
import time
import urllib.parse
import urllib.request
from collections.abc import Callable

from flask import Flask, Response, jsonify, request

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Startup diagnostics
# ---------------------------------------------------------------------------
# Logged once per gunicorn worker process.  Visible in the container console
# immediately after "Booting worker with pid: N".
app.logger.info("=" * 60)
app.logger.info("[startup] Python %s", sys.version.split()[0])
app.logger.info("[startup] PID %d", os.getpid())
app.logger.info("[startup] cwd %s", os.getcwd())
app.logger.info("[startup] tmp %s", tempfile.gettempdir())
app.logger.info("[startup] SSL cert verification DISABLED for R2 calls")
app.logger.info("=" * 60)

# ---------------------------------------------------------------------------
# SSL context for outbound R2 requests
# ---------------------------------------------------------------------------
#
# When running under `wrangler dev`, outbound HTTPS traffic from the Docker
# container is intercepted by wrangler's local networking proxy, which
# presents a self-signed TLS certificate.  Python's urllib rejects this by
# default with "certificate verify failed: self-signed certificate in
# certificate chain".
#
# The presigned R2 URLs used here are authenticated via HMAC-SHA256 signatures
# embedded in the URL query parameters, so SSL certificate verification does
# not add meaningful security for these specific calls — the signature already
# proves the URL was generated by a holder of the R2 secret key.
#
# This unverified context is used ONLY for the _download and _upload helpers
# (i.e. R2 presigned GET/PUT).  Flask's own HTTPS server is not affected.
_UNVERIFIED_SSL_CTX = ssl.create_default_context()
_UNVERIFIED_SSL_CTX.check_hostname = False
_UNVERIFIED_SSL_CTX.verify_mode = ssl.CERT_NONE


# ---------------------------------------------------------------------------
# Global exception handler — JSON instead of HTML on unhandled errors
# ---------------------------------------------------------------------------


@app.errorhandler(Exception)
def handle_unhandled_exception(e: Exception) -> tuple[Response, int]:
    """Convert ALL unhandled exceptions to a JSON error response.

    Flask's default behaviour is to return an HTML 500 page.  When the
    Cloudflare Workflow calls ``resp.json()`` on that HTML it gets a
    ``SyntaxError: Unexpected token '<'`` which hides the real cause.
    This handler ensures the Workflow always receives a JSON body with the
    actual exception type and message, making errors immediately diagnosable.

    Args:
        e: The unhandled exception that Flask caught.

    Returns:
        A 500 JSON response ``{"ok": false, "error": "<type>",
        "detail": "<message>"}``.
    """
    app.logger.exception("[error] unhandled exception in request handler: %s", e)
    return jsonify({
        "ok": False,
        "error": type(e).__name__,
        "detail": str(e),
    }), 500  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# URL display helper
# ---------------------------------------------------------------------------


def _url_display(url: str) -> str:
    """Return a safe single-line summary of a URL for logging.

    Strips the query string (which contains the HMAC signature and other
    signing parameters) so logs are readable without leaking credentials.

    Args:
        url: Full URL, typically a presigned R2 GET or PUT URL.

    Returns:
        ``scheme://host/path`` with no query string.

    Example:
        >>> _url_display("https://bucket.account.r2.cloudflarestorage.com/key?X-Amz-...")
        'https://bucket.account.r2.cloudflarestorage.com/key'
    """
    p = urllib.parse.urlparse(url)
    return f"{p.scheme}://{p.netloc}{p.path}"


# ---------------------------------------------------------------------------
# Internal HTTP helpers
# ---------------------------------------------------------------------------


def _download(url: str, dest: str) -> int:
    """Download a file from a URL to a local path using streaming reads.

    Streams the response body in 1 MiB chunks so that large video files do
    not need to fit entirely in memory before being written to disk.

    Uses ``_UNVERIFIED_SSL_CTX`` to bypass certificate verification.  See
    the module-level comment for why this is safe for presigned R2 URLs.

    Args:
        url: The URL to download from. Typically a presigned R2 GET URL.
        dest: Local filesystem path where the downloaded content is written.

    Returns:
        Total number of bytes written to ``dest``.
    """
    app.logger.info("[download] GET %s → %s", _url_display(url), dest)
    t0 = time.monotonic()
    total = 0
    with urllib.request.urlopen(url, context=_UNVERIFIED_SSL_CTX) as response, open(dest, "wb") as out:
        status = response.status
        content_length = response.headers.get("Content-Length", "unknown")
        app.logger.info("[download] HTTP %d  Content-Length: %s", status, content_length)
        while True:
            chunk = response.read(1024 * 1024)  # 1 MiB chunks
            if not chunk:
                break
            out.write(chunk)
            total += len(chunk)
    elapsed = time.monotonic() - t0
    app.logger.info("[download] complete — %d bytes in %.2fs (%.1f KB/s)",
                    total, elapsed, total / 1024 / max(elapsed, 0.001))
    return total


def _upload(url: str, src: str, content_type: str) -> None:
    """Upload a local file to a presigned URL via HTTP PUT.

    Reads the entire file into memory before sending. This is acceptable
    because each container instance processes a single video at a time and
    the container's RAM budget is large enough to hold one processed file.

    Uses ``_UNVERIFIED_SSL_CTX`` to bypass certificate verification.  See
    the module-level comment for why this is safe for presigned R2 URLs.

    Args:
        url: The presigned PUT URL to upload to. Typically an R2 presigned
            upload URL generated by the Cloudflare Workflow step.
        src: Local filesystem path of the file to upload.
        content_type: MIME type sent in the ``Content-Type`` request header
            (e.g. ``"video/mp4"`` or ``"audio/mpeg"``).
    """
    file_size = os.path.getsize(src)
    app.logger.info("[upload] PUT %s  size: %d bytes  Content-Type: %s",
                    _url_display(url), file_size, content_type)
    t0 = time.monotonic()
    with open(src, "rb") as f:
        data = f.read()
    req = urllib.request.Request(
        url,
        data=data,
        method="PUT",
        headers={"Content-Type": content_type},
    )
    with urllib.request.urlopen(req, context=_UNVERIFIED_SSL_CTX) as resp:
        upload_status = resp.status
    elapsed = time.monotonic() - t0
    app.logger.info("[upload] complete — HTTP %d in %.2fs (%.1f KB/s)",
                    upload_status, elapsed, file_size / 1024 / max(elapsed, 0.001))


# ---------------------------------------------------------------------------
# Audio stream probe helper
# ---------------------------------------------------------------------------


def _has_audio_stream(path: str) -> bool:
    """Return True if the file at ``path`` contains at least one audio stream.

    Uses ``ffprobe`` to inspect the container without decoding it.  If ffprobe
    itself fails (corrupt file, timeout, unexpected error), returns ``True`` so
    that the caller falls through to ffmpeg and gets a real diagnostic error
    rather than silently skipping a file that might actually have audio.

    Args:
        path: Local filesystem path to the video file to probe.

    Returns:
        ``True`` if at least one audio stream is present; ``False`` if the file
        is video-only (no audio track).

    Example:
        >>> _has_audio_stream("/tmp/video-only.mp4")
        False
        >>> _has_audio_stream("/tmp/with-audio.mp4")
        True
    """
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v", "quiet",
                "-select_streams", "a:0",           # first audio stream only
                "-show_entries", "stream=codec_type",
                "-of", "csv=p=0",
                path,
            ],
            capture_output=True,
            timeout=30,
        )
        has_audio = bool(result.stdout.strip())
        app.logger.info("[probe] %s — audio stream present: %s", path, has_audio)
        if result.stderr:
            app.logger.debug("[probe] ffprobe stderr: %s",
                             result.stderr.decode("utf-8", errors="replace")[:500])
        return has_audio
    except Exception as exc:
        # On any ffprobe failure, optimistically assume audio is present so
        # ffmpeg runs and produces a real diagnostic error if needed.
        app.logger.warning("[probe] ffprobe failed (%s) — assuming audio present", exc)
        return True


# ---------------------------------------------------------------------------
# Shared ffmpeg job runner
# ---------------------------------------------------------------------------


def _run_ffmpeg_job(
    input_ext: str,
    output_ext: str,
    build_cmd: Callable[[str, str], list[str]],
    output_content_type: str,
    check_audio_stream: bool = False,
) -> Response:
    """Core handler shared by /transcode, /extract-audio, and /grayscale.

    Parses the JSON request body, creates a temporary working directory,
    downloads the input file, invokes ffmpeg via subprocess, uploads the
    output file to the presigned URL, and returns a timing response.

    Logs each of the three phases (download / ffmpeg / upload) with timing
    and byte counts.  On ffmpeg failure the full stderr is logged before
    being returned in the JSON body.

    Temporary files are always removed in a ``finally`` block. This is
    critical for clean shutdown: when tini forwards SIGTERM to gunicorn,
    the worker thread completes the ``finally`` block before exiting so
    that disk space is reclaimed and no orphaned files are left behind.

    Args:
        input_ext: Filename for the downloaded input file inside the temp
            directory (e.g. ``"input"``). ffmpeg detects the container
            format from the file content, not the extension.
        output_ext: Filename for the ffmpeg output file, including the
            extension (e.g. ``"output.mp4"`` or ``"output.mp3"``).
        build_cmd: Callable that receives the absolute ``input_path`` and
            ``output_path`` strings and returns the complete ffmpeg argument
            list as ``list[str]``.
        output_content_type: MIME type used in the ``Content-Type`` header
            when uploading the output file to the presigned PUT URL.
        check_audio_stream: When ``True``, run ``ffprobe`` after downloading
            the input to verify at least one audio stream is present.  If no
            audio is found, return ``{"ok": true, "skipped": "no_audio_stream"}``
            immediately without running ffmpeg or uploading anything.  Set this
            for the ``/extract-audio`` endpoint so that video-only inputs
            (no audio track) do not cause a fatal ffmpeg error — the pipeline
            step is simply a no-op and execution continues to the next step.

    Returns:
        A Flask ``Response`` with JSON body and the appropriate HTTP status:

        - ``200`` — ffmpeg succeeded; body is
          ``{"ok": true, "duration_seconds": <float>}``.
        - ``200`` — audio probe found no audio stream (only when
          ``check_audio_stream=True``); body is
          ``{"ok": true, "duration_seconds": <float>, "skipped": "no_audio_stream"}``.
        - ``400`` — request body is missing or malformed.
        - ``500`` — ffmpeg exited with a non-zero return code; body includes
          the last 2000 characters of stderr.
        - ``504`` — ffmpeg subprocess exceeded the 1800-second timeout.
    """
    body = request.get_json(silent=True)
    if not body or "input_url" not in body or "output_url" not in body:
        app.logger.error("[job] bad request — body: %s", body)
        return jsonify({  # type: ignore[return-value]
            "ok": False,
            "error": "Request body must be JSON with 'input_url' and 'output_url'",
        }), 400

    input_url: str = body["input_url"]
    output_url: str = body["output_url"]

    tmpdir = tempfile.mkdtemp()
    input_path = os.path.join(tmpdir, input_ext)
    output_path = os.path.join(tmpdir, output_ext)

    app.logger.info("[job] ── start ──────────────────────────────────")
    app.logger.info("[job] input:  %s", _url_display(input_url))
    app.logger.info("[job] output: %s", _url_display(output_url))
    app.logger.info("[job] tmpdir: %s", tmpdir)

    wall_start = time.monotonic()

    try:
        # ── Step 1/3: download input ──────────────────────────────
        app.logger.info("[job] step 1/3 — download input")
        input_bytes = _download(input_url, input_path)

        # ── Step 1b/3: optional audio stream probe ────────────────
        # Only used by /extract-audio. If the transcoded MP4 has no audio
        # track (video-only source), ffmpeg would fail with exit 234 and
        # "Output file does not contain any stream". We detect this early
        # with ffprobe and return a successful no-op so the Workflow step
        # does not throw and the pipeline continues to grayscale.
        if check_audio_stream:
            app.logger.info("[job] step 1b/3 — probing for audio streams")
            if not _has_audio_stream(input_path):
                elapsed = time.monotonic() - wall_start
                app.logger.info(
                    "[job] no audio stream in input — skipping extraction "
                    "(r2_audio_key will be recorded in D1 but file will not "
                    "be uploaded to R2)"
                )
                return jsonify({
                    "ok": True,
                    "duration_seconds": elapsed,
                    "skipped": "no_audio_stream",
                })

        # ── Step 2/3: run ffmpeg ──────────────────────────────────
        cmd = build_cmd(input_path, output_path)
        app.logger.info("[job] step 2/3 — ffmpeg: %s", " ".join(cmd))
        t_ffmpeg = time.monotonic()
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                check=True,
                timeout=1800,
            )
            ffmpeg_elapsed = time.monotonic() - t_ffmpeg
            output_bytes = os.path.getsize(output_path)
            app.logger.info("[job] step 2/3 — ffmpeg done in %.2fs  output: %d bytes",
                            ffmpeg_elapsed, output_bytes)
            # Log ffmpeg stderr at DEBUG level even on success — useful for
            # diagnosing codec warnings or unusual input characteristics.
            if result.stderr:
                stderr_preview = result.stderr.decode("utf-8", errors="replace")[-1000:]
                app.logger.debug("[job] ffmpeg stderr (last 1000 chars):\n%s", stderr_preview)
        except subprocess.CalledProcessError as e:
            stderr_text = e.stderr.decode("utf-8", errors="replace")
            app.logger.error("[job] ffmpeg FAILED — exit code %d\nstderr (last 2000):\n%s",
                             e.returncode, stderr_text[-2000:])
            return jsonify({  # type: ignore[return-value]
                "ok": False,
                "error": f"ffmpeg exited with code {e.returncode}",
                "stderr": stderr_text[-2000:],
            }), 500
        except subprocess.TimeoutExpired:
            app.logger.error("[job] ffmpeg TIMED OUT after 1800s")
            return jsonify({  # type: ignore[return-value]
                "ok": False,
                "error": "ffmpeg timed out after 30 minutes",
            }), 504

        # ── Step 3/3: upload output ───────────────────────────────
        app.logger.info("[job] step 3/3 — upload output (%d bytes)", output_bytes)
        _upload(output_url, output_path, output_content_type)

        total_elapsed = time.monotonic() - wall_start
        app.logger.info(
            "[job] ── complete — input %d B  output %d B  total %.2fs ──",
            input_bytes, output_bytes, total_elapsed,
        )
        return jsonify({"ok": True, "duration_seconds": total_elapsed})

    finally:
        # Clean up all temporary files regardless of success or failure.
        # Using individual try/except blocks ensures that a failure to
        # remove one file does not prevent the others from being removed.
        for path in (input_path, output_path):
            try:
                os.remove(path)
                app.logger.debug("[job] cleaned up %s", path)
            except FileNotFoundError:
                pass
        try:
            os.rmdir(tmpdir)
            app.logger.debug("[job] removed tmpdir %s", tmpdir)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@app.route("/health")
def health() -> Response:
    """Readiness probe used by Cloudflare Containers and the Workflow.

    Returns a 200 response indicating the server is running and ready to
    accept video-processing requests. The Container runtime polls this
    endpoint during ``startAndWaitForPorts()`` to confirm Flask is serving
    before the Workflow sends actual work requests.

    Returns:
        A JSON response ``{"ok": true}`` with HTTP 200.
    """
    app.logger.debug("[health] GET /health → 200")
    return jsonify({"ok": True})


@app.route("/transcode", methods=["POST"])
def transcode() -> Response:
    """Transcode a video to H.264/AAC MP4 format.

    Downloads the input video from a presigned R2 GET URL, transcodes it
    to H.264 video with AAC audio in an MP4 container using libx264 and
    the aac encoder, then uploads the result to a presigned R2 PUT URL.

    This endpoint accepts any video format supported by ffmpeg as input.
    The output is always an MP4 file suitable for subsequent processing
    steps (/extract-audio and /grayscale).

    Request JSON:
        input_url (str): Presigned GET URL for the source video in R2
            (e.g. the original uploaded file at ``incoming/{videoId}.{ext}``).
        output_url (str): Presigned PUT URL for the transcoded MP4 in R2
            (e.g. ``video/{videoId}.mp4``).

    Returns:
        200 JSON ``{"ok": true, "duration_seconds": <float>}`` on success.
        500 JSON ``{"ok": false, "error": "...", "stderr": "..."}`` if
            ffmpeg exits with a non-zero return code (truncated to last
            2000 chars of stderr).
        504 JSON ``{"ok": false, "error": "ffmpeg timed out ..."}`` if
            the subprocess exceeds 1800 seconds.

    Example::

        POST /transcode
        Content-Type: application/json

        {"input_url": "https://r2.example.com/...", "output_url": "https://r2.example.com/..."}
    """
    app.logger.info("[transcode] POST /transcode received")
    return _run_ffmpeg_job(
        input_ext="input",
        output_ext="output.mp4",
        build_cmd=lambda inp, out: [
            "ffmpeg",
            "-i", inp,
            "-c:v", "libx264",
            "-c:a", "aac",
            "-y", out,
        ],
        output_content_type="video/mp4",
    )


@app.route("/extract-audio", methods=["POST"])
def extract_audio() -> Response:
    """Extract the audio track from a video as an MP3 file.

    Downloads a transcoded MP4 from a presigned R2 GET URL, strips the
    video stream entirely (``-vn``), re-encodes the audio with libmp3lame,
    and uploads the resulting MP3 to a presigned R2 PUT URL.

    This step runs after /transcode so the input is always an H.264/AAC
    MP4 with a guaranteed audio stream.

    Request JSON:
        input_url (str): Presigned GET URL for the transcoded MP4 in R2
            (e.g. ``video/{videoId}.mp4``).
        output_url (str): Presigned PUT URL for the extracted MP3 in R2
            (e.g. ``audio/{videoId}.mp3``).

    Returns:
        200 JSON ``{"ok": true, "duration_seconds": <float>}`` on success.
        500 JSON ``{"ok": false, "error": "...", "stderr": "..."}`` if
            ffmpeg exits with a non-zero return code.
        504 JSON ``{"ok": false, "error": "ffmpeg timed out ..."}`` if
            the subprocess exceeds 1800 seconds.

    Example::

        POST /extract-audio
        Content-Type: application/json

        {"input_url": "https://r2.example.com/...", "output_url": "https://r2.example.com/..."}
    """
    app.logger.info("[extract-audio] POST /extract-audio received")
    return _run_ffmpeg_job(
        input_ext="input",
        output_ext="output.mp3",
        build_cmd=lambda inp, out: [
            "ffmpeg",
            "-i", inp,
            "-vn",
            "-c:a", "libmp3lame",
            "-y", out,
        ],
        output_content_type="audio/mpeg",
        # Probe for audio before running ffmpeg. If the input has no audio
        # stream (video-only), skip gracefully instead of failing with exit
        # code 234 "Output file does not contain any stream".
        check_audio_stream=True,
    )


@app.route("/grayscale", methods=["POST"])
def grayscale() -> Response:
    """Apply a grayscale filter to a video, preserving the audio track.

    Downloads an MP4 from a presigned R2 GET URL, applies the
    ``format=gray`` video filter (which converts the YUV colour space to
    grayscale), copies the audio stream without re-encoding (``-c:a copy``),
    and uploads the result to a presigned R2 PUT URL.

    This is the final processing step before the video is uploaded to
    Cloudflare Stream. Copying audio avoids an unnecessary encode cycle
    since the audio track was already encoded by /transcode.

    Request JSON:
        input_url (str): Presigned GET URL for the transcoded MP4 in R2
            (e.g. ``video/{videoId}.mp4``).
        output_url (str): Presigned PUT URL for the grayscale MP4 in R2
            (e.g. ``bwvideo/{videoId}.mp4``).

    Returns:
        200 JSON ``{"ok": true, "duration_seconds": <float>}`` on success.
        500 JSON ``{"ok": false, "error": "...", "stderr": "..."}`` if
            ffmpeg exits with a non-zero return code.
        504 JSON ``{"ok": false, "error": "ffmpeg timed out ..."}`` if
            the subprocess exceeds 1800 seconds.

    Example::

        POST /grayscale
        Content-Type: application/json

        {"input_url": "https://r2.example.com/...", "output_url": "https://r2.example.com/..."}
    """
    app.logger.info("[grayscale] POST /grayscale received")
    return _run_ffmpeg_job(
        input_ext="input",
        output_ext="output.mp4",
        build_cmd=lambda inp, out: [
            "ffmpeg",
            "-i", inp,
            "-vf", "format=gray",
            "-c:a", "copy",
            "-y", out,
        ],
        output_content_type="video/mp4",
    )
