"""Flask HTTP server wrapping ffmpeg for the video-processing-pipeline container.

This server runs inside a Cloudflare Container alongside the ffmpeg binary.
The Cloudflare Workflow sends HTTP requests to this server to perform
CPU-intensive video processing tasks. Each endpoint downloads an input file
from a presigned R2 GET URL, runs an ffmpeg command, and uploads the result
to a presigned R2 PUT URL.

Endpoints:
    GET  /health         — readiness probe; returns ``{"ok": true}``
    POST /transcode      — transcode any video to H.264/AAC MP4
    POST /extract-audio  — extract audio track to MP3
    POST /grayscale      — apply grayscale filter, preserve audio

Request body (all POST endpoints)::

    {"input_url": "<presigned-get-url>", "output_url": "<presigned-put-url>"}

Success response (HTTP 200)::

    {"ok": true, "duration_seconds": <float>}

Error response (HTTP 500 or 504)::

    {"ok": false, "error": "<message>", "stderr": "<truncated-ffmpeg-stderr>"}

Signal handling:
    tini (PID 1) forwards SIGTERM to gunicorn, which shuts down workers
    gracefully. The ``finally`` block in each route ensures temporary files
    are cleaned up even when a request is interrupted mid-flight.

Timeout:
    Each ffmpeg invocation has a 1800-second (30-minute) subprocess timeout.
    gunicorn's ``--timeout`` flag is also set to 1800 seconds to match.
"""

import os
import subprocess
import tempfile
import time
import urllib.request
from collections.abc import Callable

from flask import Flask, Response, jsonify, request

app = Flask(__name__)


# ---------------------------------------------------------------------------
# Internal HTTP helpers
# ---------------------------------------------------------------------------


def _download(url: str, dest: str) -> None:
    """Download a file from a URL to a local path using streaming reads.

    Streams the response body in 1 MiB chunks so that large video files do
    not need to fit entirely in memory before being written to disk.

    Args:
        url: The URL to download from. Typically a presigned R2 GET URL.
        dest: Local filesystem path where the downloaded content is written.
    """
    with urllib.request.urlopen(url) as response, open(dest, "wb") as out:
        while True:
            chunk = response.read(1024 * 1024)  # 1 MiB chunks
            if not chunk:
                break
            out.write(chunk)


def _upload(url: str, src: str, content_type: str) -> None:
    """Upload a local file to a presigned URL via HTTP PUT.

    Reads the entire file into memory before sending. This is acceptable
    because each container instance processes a single video at a time and
    the container's RAM budget is large enough to hold one processed file.

    Args:
        url: The presigned PUT URL to upload to. Typically an R2 presigned
            upload URL generated by the Cloudflare Workflow step.
        src: Local filesystem path of the file to upload.
        content_type: MIME type sent in the ``Content-Type`` request header
            (e.g. ``"video/mp4"`` or ``"audio/mpeg"``).
    """
    with open(src, "rb") as f:
        data = f.read()
    req = urllib.request.Request(
        url,
        data=data,
        method="PUT",
        headers={"Content-Type": content_type},
    )
    urllib.request.urlopen(req)


# ---------------------------------------------------------------------------
# Shared ffmpeg job runner
# ---------------------------------------------------------------------------


def _run_ffmpeg_job(
    input_ext: str,
    output_ext: str,
    build_cmd: Callable[[str, str], list[str]],
    output_content_type: str,
) -> Response:
    """Core handler shared by /transcode, /extract-audio, and /grayscale.

    Parses the JSON request body, creates a temporary working directory,
    downloads the input file, invokes ffmpeg via subprocess, uploads the
    output file to the presigned URL, and returns a timing response.

    Temporary files are always removed in a ``finally`` block. This is
    critical for clean shutdown: when tini forwards SIGTERM to gunicorn,
    the worker thread completes the ``finally`` block before exiting so
    that disk space is reclaimed and no orphaned files are left behind.

    Args:
        input_ext: Filename for the downloaded input file inside the temp
            directory (e.g. ``"input"``). ffmpeg detects the container
            format from the file content, not the extension.
        output_ext: Filename for the ffmpeg output file, including the
            extension (e.g. ``"output.mp4"`` or ``"output.mp3"``).
        build_cmd: Callable that receives the absolute ``input_path`` and
            ``output_path`` strings and returns the complete ffmpeg argument
            list as ``list[str]``.
        output_content_type: MIME type used in the ``Content-Type`` header
            when uploading the output file to the presigned PUT URL.

    Returns:
        A Flask ``Response`` with JSON body and the appropriate HTTP status:

        - ``200`` — ffmpeg succeeded; body is
          ``{"ok": true, "duration_seconds": <float>}``.
        - ``400`` — request body is missing or malformed.
        - ``500`` — ffmpeg exited with a non-zero return code; body includes
          the last 2000 characters of stderr.
        - ``504`` — ffmpeg subprocess exceeded the 1800-second timeout.
    """
    body = request.get_json(silent=True)
    if not body or "input_url" not in body or "output_url" not in body:
        return jsonify({
            "ok": False,
            "error": "Request body must be JSON with 'input_url' and 'output_url'",
        }), 400  # type: ignore[return-value]

    input_url: str = body["input_url"]
    output_url: str = body["output_url"]

    tmpdir = tempfile.mkdtemp()
    input_path = os.path.join(tmpdir, input_ext)
    output_path = os.path.join(tmpdir, output_ext)

    start = time.monotonic()

    try:
        _download(input_url, input_path)

        cmd = build_cmd(input_path, output_path)

        try:
            subprocess.run(
                cmd,
                capture_output=True,
                check=True,
                timeout=1800,
            )
        except subprocess.CalledProcessError as e:
            stderr_text = e.stderr.decode("utf-8", errors="replace")[-2000:]
            return jsonify({  # type: ignore[return-value]
                "ok": False,
                "error": f"ffmpeg exited with code {e.returncode}",
                "stderr": stderr_text,
            }), 500
        except subprocess.TimeoutExpired:
            return jsonify({  # type: ignore[return-value]
                "ok": False,
                "error": "ffmpeg timed out after 30 minutes",
            }), 504

        _upload(output_url, output_path, output_content_type)

        elapsed = time.monotonic() - start
        return jsonify({"ok": True, "duration_seconds": elapsed})

    finally:
        # Clean up all temporary files regardless of success or failure.
        # Using individual try/except blocks ensures that a failure to
        # remove one file does not prevent the others from being removed.
        for path in (input_path, output_path):
            try:
                os.remove(path)
            except FileNotFoundError:
                pass
        try:
            os.rmdir(tmpdir)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@app.route("/health")
def health() -> Response:
    """Readiness probe used by Cloudflare Containers and the Workflow.

    Returns a 200 response indicating the server is running and ready to
    accept video-processing requests. The Workflow calls this endpoint
    before dispatching ffmpeg work to verify the container has started
    successfully.

    Returns:
        A JSON response ``{"ok": true}`` with HTTP 200.
    """
    return jsonify({"ok": True})


@app.route("/transcode", methods=["POST"])
def transcode() -> Response:
    """Transcode a video to H.264/AAC MP4 format.

    Downloads the input video from a presigned R2 GET URL, transcodes it
    to H.264 video with AAC audio in an MP4 container using libx264 and
    the aac encoder, then uploads the result to a presigned R2 PUT URL.

    This endpoint accepts any video format supported by ffmpeg as input.
    The output is always an MP4 file suitable for subsequent processing
    steps (/extract-audio and /grayscale).

    Request JSON:
        input_url (str): Presigned GET URL for the source video in R2
            (e.g. the original uploaded file at ``incoming/{videoId}.{ext}``).
        output_url (str): Presigned PUT URL for the transcoded MP4 in R2
            (e.g. ``video/{videoId}.mp4``).

    Returns:
        200 JSON ``{"ok": true, "duration_seconds": <float>}`` on success.
        500 JSON ``{"ok": false, "error": "...", "stderr": "..."}`` if
            ffmpeg exits with a non-zero return code (truncated to last
            2000 chars of stderr).
        504 JSON ``{"ok": false, "error": "ffmpeg timed out ..."}`` if
            the subprocess exceeds 1800 seconds.

    Example::

        POST /transcode
        Content-Type: application/json

        {"input_url": "https://r2.example.com/...", "output_url": "https://r2.example.com/..."}
    """
    return _run_ffmpeg_job(
        input_ext="input",
        output_ext="output.mp4",
        build_cmd=lambda inp, out: [
            "ffmpeg",
            "-i", inp,
            "-c:v", "libx264",
            "-c:a", "aac",
            "-y", out,
        ],
        output_content_type="video/mp4",
    )


@app.route("/extract-audio", methods=["POST"])
def extract_audio() -> Response:
    """Extract the audio track from a video as an MP3 file.

    Downloads a transcoded MP4 from a presigned R2 GET URL, strips the
    video stream entirely (``-vn``), re-encodes the audio with libmp3lame,
    and uploads the resulting MP3 to a presigned R2 PUT URL.

    This step runs after /transcode so the input is always an H.264/AAC
    MP4 with a guaranteed audio stream.

    Request JSON:
        input_url (str): Presigned GET URL for the transcoded MP4 in R2
            (e.g. ``video/{videoId}.mp4``).
        output_url (str): Presigned PUT URL for the extracted MP3 in R2
            (e.g. ``audio/{videoId}.mp3``).

    Returns:
        200 JSON ``{"ok": true, "duration_seconds": <float>}`` on success.
        500 JSON ``{"ok": false, "error": "...", "stderr": "..."}`` if
            ffmpeg exits with a non-zero return code.
        504 JSON ``{"ok": false, "error": "ffmpeg timed out ..."}`` if
            the subprocess exceeds 1800 seconds.

    Example::

        POST /extract-audio
        Content-Type: application/json

        {"input_url": "https://r2.example.com/...", "output_url": "https://r2.example.com/..."}
    """
    return _run_ffmpeg_job(
        input_ext="input",
        output_ext="output.mp3",
        build_cmd=lambda inp, out: [
            "ffmpeg",
            "-i", inp,
            "-vn",
            "-c:a", "libmp3lame",
            "-y", out,
        ],
        output_content_type="audio/mpeg",
    )


@app.route("/grayscale", methods=["POST"])
def grayscale() -> Response:
    """Apply a grayscale filter to a video, preserving the audio track.

    Downloads an MP4 from a presigned R2 GET URL, applies the
    ``format=gray`` video filter (which converts the YUV colour space to
    grayscale), copies the audio stream without re-encoding (``-c:a copy``),
    and uploads the result to a presigned R2 PUT URL.

    This is the final processing step before the video is uploaded to
    Cloudflare Stream. Copying audio avoids an unnecessary encode cycle
    since the audio track was already encoded by /transcode.

    Request JSON:
        input_url (str): Presigned GET URL for the transcoded MP4 in R2
            (e.g. ``video/{videoId}.mp4``).
        output_url (str): Presigned PUT URL for the grayscale MP4 in R2
            (e.g. ``bwvideo/{videoId}.mp4``).

    Returns:
        200 JSON ``{"ok": true, "duration_seconds": <float>}`` on success.
        500 JSON ``{"ok": false, "error": "...", "stderr": "..."}`` if
            ffmpeg exits with a non-zero return code.
        504 JSON ``{"ok": false, "error": "ffmpeg timed out ..."}`` if
            the subprocess exceeds 1800 seconds.

    Example::

        POST /grayscale
        Content-Type: application/json

        {"input_url": "https://r2.example.com/...", "output_url": "https://r2.example.com/..."}
    """
    return _run_ffmpeg_job(
        input_ext="input",
        output_ext="output.mp4",
        build_cmd=lambda inp, out: [
            "ffmpeg",
            "-i", inp,
            "-vf", "format=gray",
            "-c:a", "copy",
            "-y", out,
        ],
        output_content_type="video/mp4",
    )
