/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime=false --strict-vars=false` (hash: bb66f7c38b809ebd486715d862b63507)
interface __BaseEnv_Env {
  BUCKET: R2Bucket;
  DB: D1Database;
  ASSETS: Fetcher;
  CF_ACCOUNT_ID: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  CF_API_TOKEN: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_API_TOKEN: string;
  CLOUDFLARE_WORKERS_DOMAIN: string;
  CLOUDFLARE_TEAM_DOMAIN: string;
  FFMPEG_CONTAINER: DurableObjectNamespace /* FFmpegContainer */;
  VIDEO_WORKFLOW: Workflow /* VideoProcessingWorkflow */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "FFmpegContainer";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "CF_ACCOUNT_ID"
        | "R2_ACCESS_KEY_ID"
        | "R2_SECRET_ACCESS_KEY"
        | "CF_API_TOKEN"
        | "CLOUDFLARE_ACCOUNT_ID"
        | "CLOUDFLARE_API_TOKEN"
        | "CLOUDFLARE_WORKERS_DOMAIN"
        | "CLOUDFLARE_TEAM_DOMAIN"
      >
    > {}
}
