// Generated by Wrangler by running `wrangler types`
// (This stub is maintained manually until `wrangler types` overwrites it.)
//
// Bindings and vars mirror wrangler.jsonc exactly.  If you add a new binding
// or var to wrangler.jsonc, re-run `wrangler types` or update this file to
// match — TypeScript will not catch a mismatch at runtime.

interface Env {
  // ---- Bindings ----
  /** D1 database for video metadata storage. */
  DB: D1Database;
  /** R2 bucket for raw uploads and processed video files. */
  BUCKET: R2Bucket;
  /**
   * Worker Assets binding — serves the React SPA.
   * Used via `c.env.ASSETS.fetch(c.req.raw)` in the catch-all route.
   */
  ASSETS: Fetcher;
  /**
   * Workflow binding for creating and managing `VideoProcessingWorkflow`
   * instances.
   */
  VIDEO_WORKFLOW: Workflow;
  /**
   * Durable Object namespace for the `FFmpegContainer` class.
   * Each video gets its own named instance via `getByName(videoId)`.
   */
  FFMPEG_CONTAINER: DurableObjectNamespace;

  // ---- Vars (plaintext, injected by generate-wrangler from Terraform outputs) ----
  /**
   * Cloudflare Access team domain used by `cloudflareAccess` to fetch the
   * JWKS for JWT verification (e.g. `"myteam.cloudflareaccess.com"`).
   */
  CLOUDFLARE_TEAM_DOMAIN: string;
  /** Cloudflare account ID — used when calling the Stream copy-from-URL API. */
  CF_ACCOUNT_ID: string;
  /**
   * S3-compatible access key ID for the R2 bucket.
   * Used by the presigned URL helper to sign PUT requests.
   */
  R2_ACCESS_KEY_ID: string;
  /**
   * S3-compatible secret access key for the R2 bucket.
   * Used by the presigned URL helper to sign PUT requests.
   */
  R2_SECRET_ACCESS_KEY: string;
  /**
   * Cloudflare API token with Stream Write permission.
   * Used by the Workflow when uploading the grayscale video to Stream.
   */
  CF_API_TOKEN: string;
}
